### ISSUE TITLE
Definição do Roadmap!

### ISSUE THREAD

**Issue by manzoliric** [training-center/react-study-group#4]
Boa tarde galera, estou abrindo essa Issue para decidir como será o Roadmap, podem dar ideias :grin:

**Comment by Gabriellpweb** [comment]
Algumas sugestões:
O que é? Pra que serve? Como funciona? Dependencias minimas?

**Comment by frontendwizard** [comment]
Minha sugestão é seguirmos o currículo proposto pelo freecodecamp.org. Mais ou menos algo nessa ordem:

* Sintaxe JSX
* Components React
  * Stateless
  * Classe
* Props
  * proptypes
  * defaultProps
* State
* Fazer um contador com state
* Inputs controladas
* Métodos do ciclo de vida de um component
* Gerenciando estilos
* Renderizando condicionalmente
  * if/else
  * &&
  * Operador ternário
* manipulando children
  * React.Children.map
* SSR

**Comment by manzoliric** [comment]
Vamos lá, se eu falar alguma besteira, me corrijam hahaha

Roadmap é uma especie de passos que podemos seguir para aprender algo, exemplo - > https://camo.githubusercontent.com/04ad65322cfd84ad30a3173e15d8b0cacff0d6c2/68747470733a2f2f692e696d6775722e636f6d2f5772664c45536d2e706e67

Podemos fazer um de React e acho que seria mais fácil escrito, exemplo:

Dependências minimas para se começar o Roadmap -> Basic de JavaScript, como funções, objetos, conhecer o básico do this e etc...

RoadMap React -> JSX, WebPack, Props, Keys, Eventos, State, Stateful vs stateless e etc.. 

Ou podemos pegar algo já pronto como o FreeCodeCamp -> https://beta.freecodecamp.org/en/challenges/react/create-a-simple-jsx-element

Um exemplo de RoadMap bem interessante é do PHP Studys Group que é nivelado em Iniciante, Intermediário e Avançado e os assuntos são bem dividos -> https://github.com/training-center/php-study-group/tree/master/material_de_apoio/roadmap

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by manzoliric** [comment]
Pode encerrar, obrigado @Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @manzolirch
