### ISSUE TITLE
Definição dos Projetos!

### ISSUE THREAD

**Issue by manzoliric** [training-center/react-study-group#5]
Boa tarde galera, estou abrindo essa Issue para decidir os Projetos que serão criados, podem dar ideias :grin:

Acho legal primeiro nivelar, entre Iniciante, Intermediário e Avançado e depois assim definir cada projeto para um nível.

Exemplos de Projetos: Calculadora de IMC, To Do List, GitHub Api e etc...

**Comment by Diego-Brocanelli** [comment]
Olá, @manzolirch .

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by manzoliric** [comment]
Pode encerrar, obrigado @Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @manzolirch
