### ISSUE TITLE
Faltando link para o formulário de nível de conhecimento

### ISSUE THREAD

**Issue by imbrn** [training-center/react-study-group#6]
Na seção **Como participar**, o link para o formulário de avaliação do nível de conhecimento está faltando o endereço.

**Comment by manzoliric** [comment]
Fala @bruno02221 estamos sem formulário mesmo, alterei lá que o passo é apenas entrar no Slack do TC e ir pro #react-studies.

**Comment by imbrn** [comment]
Certo então, entendi.

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by imbrn** [comment]
Sim, pode fechar

**Comment by manzoliric** [comment]
Pode encerrar, obrigado @Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @manzolirch
